[workspace]
members = [
    "programs/anchor-nft-staking"
]
resolver = "2"

[workspace.dependencies]
proc-macro2 = "=1.0.66"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
